Imports System.IO
Imports System.IO.StreamWriter

Partial Class Report_frmReportProcurement
    Inherits System.Web.UI.Page

    Dim ItemRequisitionData As New clsItemRequisitionDataAccess()

    Protected Sub btnShowReport_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnShowReport.Click

        grdQueryResult.DataSource = ""
        grdQueryResult.DataBind()

        Dim DateFrom, DateTo As DateTime

        Try
            If (txtDateFrom.Text = "" And txtDateTo.Text <> "") Or (txtDateFrom.Text <> "" And txtDateTo.Text = "") Then
                MessageBox("Date From & Date To Both Parameters Required.")
                Exit Sub
            End If

            If txtDateFrom.Text = "" Then
                DateFrom = "1/1/1900"
            Else
                DateFrom = txtDateFrom.Text
            End If

            If txtDateTo.Text = "" Then
                DateTo = "1/1/2099"
            Else
                DateTo = txtDateTo.Text
            End If

            grdQueryResult.DataSource = ItemRequisitionData.fnGetAggregatedDelivery(DateFrom, DateTo)
            grdQueryResult.DataBind()
        Catch ex As Exception
            MessageBox(ex.Message)
        End Try

    End Sub

    Private Sub MessageBox(ByVal strMsg As String)
        Dim lbl As New System.Web.UI.WebControls.Label
        lbl.Text = "<script language='javascript'>" & Environment.NewLine _
                   & "window.alert(" & "'" & strMsg & "'" & ")</script>"
        Page.Controls.Add(lbl)
    End Sub

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim MenuIDs As String

        MenuIDs = Session("PermittedMenus")

        If InStr(MenuIDs, "RptProcurement~") = 0 Then
            Response.Redirect("~\frmAILogin.aspx")
        End If

        If Not IsPostBack Then
            txtDateFrom.Text = Now.Month.ToString() & "/1/" & Now.Year.ToString()
            txtDateTo.Text = Now.Date.ToString()
        End If
    End Sub

    Protected Sub btnCancel_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnCancel.Click
        ClearForm()
    End Sub

    Protected Sub ClearForm()
        txtDateFrom.Text = ""
        txtDateTo.Text = ""
        grdQueryResult.DataSource = ""
        grdQueryResult.DataBind()
    End Sub

    Protected Sub btnExportReport_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnExportReport.Click
        ExportToExcel(grdQueryResult)
    End Sub

    Protected Sub ExportToExcel(ByVal gridview As System.Web.UI.WebControls.GridView)
        Try
            Dim sw As New StringWriter()
            Dim hw As New System.Web.UI.HtmlTextWriter(sw)
            Dim frm As HtmlForm = New HtmlForm()

            Page.Response.AddHeader("content-disposition", "attachment;filename=DeliveryReport.xls")
            Page.Response.ContentType = "application/ms-excel"
            Page.Response.Charset = ""
            Page.EnableViewState = False
            frm.Attributes("runat") = "server"
            Controls.Add(frm)
            frm.Controls.Add(grdQueryResult)
            frm.RenderControl(hw)
            Response.Write(sw.ToString())
            Response.End()
        Catch ex As Exception
            MessageBox(ex.Message)
        End Try
      
    End Sub

    Public Shared Sub ExportToExel(ByVal grdvw As GridView, ByVal rptname As String)

        Dim attachment As String = "attachment; filename=" & rptname & ".xls"
        HttpContext.Current.Response.ClearContent()
        HttpContext.Current.Response.AddHeader("content-disposition", attachment)
        HttpContext.Current.Response.ContentType = "application/ms-excel"
        Dim sw As New StringWriter()
        Dim htw As New HtmlTextWriter(sw)

        grdvw.AllowSorting = False
        grdvw.AllowPaging = False
        grdvw.AutoGenerateSelectButton = False
        grdvw.AutoGenerateEditButton = False
        grdvw.AutoGenerateDeleteButton = False
        grdvw.DataBind()

        ' Create a form to contain the grid
        Dim frm As New HtmlForm()
        grdvw.Parent.Controls.Add(frm)
        frm.Attributes("runat") = "server"
        frm.Controls.Add(grdvw)

        frm.RenderControl(htw)
        'grdvw.RenderControl(htw)
        HttpContext.Current.Response.Write(sw.ToString())
        HttpContext.Current.Response.[End]()

    End Sub

End Class
